name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libegl1-mesa libgl1-mesa-glx xvfb xauth  # Install Xvfb and additional tools
        sudo apt-get install -y libxkbcommon-x11-0  # Install additional dependencies for PySide6

    - name: List installed libraries
      run: |
        dpkg -l | grep libegl
        dpkg -l | grep libgl
        dpkg -l | grep libxkbcommon

    - name: Run flake8
      run: |
        . .venv/bin/activate
        pip install flake8
        flake8 app/ tests/

    - name: Run tests with Xvfb
      env:
        DISPLAY: ":99"  # Set the DISPLAY environment variable
      run: |
        . .venv/bin/activate
        # Start Xvfb in the background
        Xvfb :99 -screen 0 1920x1080x24 &
        sleep 3  # Give Xvfb some time to start
        pytest --maxfail=1 --disable-warnings -v
