name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libegl1-mesa libgl1-mesa-glx xvfb  # Install Xvfb and required libraries

    - name: Install dependencies
      run: |
        python -m venv .venv
        . .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run flake8
      run: |
        . .venv/bin/activate
        pip install flake8
        flake8 app/ tests/

    - name: Run tests with Xvfb
      run: |
        . .venv/bin/activate
        pip install pytest-qt
        # Start Xvfb and run pytest
        xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' pytest
