name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libegl1-mesa libgl1-mesa-glx xvfb xauth
        sudo apt-get install -y libxkbcommon-x11-0

    - name: Create and activate virtual environment
      run: |
        python -m venv .venv
        . .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: List installed libraries
      run: |
        dpkg -l | grep libegl
        dpkg -l | grep libgl
        dpkg -l | grep libxkbcommon

    - name: Run flake8
      run: |
        . .venv/bin/activate
        flake8 app/ tests/

