name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libegl1-mesa libgl1-mesa-glx

    - name: Install dependencies
      run: |
        python -m venv .venv
        . .venv/bin/activate  # Use a dot for activating the virtual environment in Linux
        python -m pip install --upgrade pip  # Upgrade pip to the latest version
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run flake8
      run: |
        . .venv/bin/activate  # Use a dot for activating the virtual environment in Linux
        pip install flake8
        flake8 app/ tests/

    - name: Run tests
      run: |
        . .venv/bin/activate  # Use a dot for activating the virtual environment in Linux
        pip install pytest-qt  # Ensure pytest-qt is installed
        pytest
